# Generated by Django 5.1.1 on 2024-09-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='test',
            new_name='text',
        ),
    ]
